schema_version: 1

context:
  name: konnektor
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/OpenFreeEnergy/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9d5c6f2505e0b4e325ed3e39007f93497ead346e13bf4dbe77ba16ca835923b3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - gufe >=1,<2
    - numpy
    - rdkit
    - networkx
    - scikit-mol >=0.5.5  # https://github.com/EBjerrum/scikit-mol/pull/68
    - scikit-learn
    - ipycytoscape

tests:
  - python:
      imports:
        - konnektor
      python_version: ${{ python_min }}.*
      pip_check: false
  - requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
    script:
      - pytest --pyargs konnektor

about:
  summary: Konnektor is a package for calculating networks.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/OpenFreeEnergy/konnektor

extra:
  recipe-maintainers:
    - atravitz
    - mikemhenry
    - IAlibay
    - RiesBen
